version: '3.8'

services:
  postgres:
    restart: 'always'
    image: postgres:15.4-alpine
    networks:
      - db
      - server
    volumes:
      - ./todo.sql:/docker-entrypoint-initdb.d/schema.sql
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      timeout: 2s
      interval: 5s
      retries: 10
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: 'always'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:9777"
    depends_on:
      - postgres
    networks:
      - db

  server:
    restart: 'always'
    image: ai23m046/zephyr_server
    networks:
      - server
      - ui
    ports:
      - "8080:80"
    links:
      - "postgres:database"

  frontend:
    restart: 'always'
    image: ai23m046/zephyr_ui
    networks:
      - ui
    ports:
      - "8088:8080"
    links:
      - "server:api"

networks:
  db:
  server:
  ui:
